os: linux
dist: focal
language: python

python:
  - 3.8
#
install:
  - sudo apt -y install python3-distutils
  - sudo apt -y install python3-pip
  - sudo apt install -y git
  - git clone https://github.com/kivy/buildozer.git
  - python3 -m site
  - ls -l
  - cd buildozer
  - ls -l
  - python3 setup.py install
  - ls -l
  - cd ..
  - ls -l

  - sudo apt update
  - sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
  - pip3 install --upgrade Cython==0.29.19 virtualenv
  - export PATH=$PATH:~/.local/bin/
  - ls -la
  - echo "TODO COMPILE 32bit"
  - yes | cp -f buildozer-32bit.spec buildozer.spec
  - yes | buildozer android debug
  - ls -la
  - ls bin/ -l
  - echo "TODO"
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/registrator-0.1-armeabi-v7a-debug.apk" --tag_name "v.0.1"
  - echo "TODO COMPILE 64bit"
  - ls -la
  - rm -r -f .buildozer
  - ls -la
  - yes | cp -f buildozer-64bit.spec buildozer.spec
  - yes | buildozer android debug
  - ls -la
  - ls bin/ -l
  - echo "TODO"
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/registrator-0.1-arm64-v8a-debug.apk" --tag_name "v.0.1"
script:
  - echo "OK"
cache:
      directories:
        - $HOME/.m2
- echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
- cat $HOME/.m2/settings.xml